# Generated by Django 4.0.5 on 2022-08-19 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='todo_until',
            new_name='expired_at',
        ),
    ]
